### ISSUE TITLE
Can't use mailinator.com anymore

### ISSUE THREAD

**Issue by spaze** [setya5785/OPGen#1]
Hey,

I've now removed `...@mailinator.com` from my `oprah-proxy.py` and have replaced it with `...@se0310.surfeasy.vpn` as it seems that mailinator.com got blacklisted and is not working anymore.

Thought I'd let you know so you can accommodate too. See this commit
https://github.com/spaze/oprah-proxy/commit/e39fdae7a283165d5ab097c7226651f71300b8c0 for the change.

Cheers!

**Comment by setya5785** [comment]
thank you for the heads up, i'll adjust my code to reflect this.
https://github.com/setya5785/OPGen/commit/7220ba58fcda6aa0b3332f8bc36ea54c4c7b1e4d
